### ISSUE TITLE
error when testing 130x130 pixel

### ISSUE THREAD

**Issue by zsif09** [ilyakava/kaggle-dr#2]
THEANO_FLAGS='floatX=float32,device=gpu0' python -m my_code.predict -M models/ed3ffc4e-vgg_mini7b_leak_sig_ep-nnrank-re-kappa-sym-bestkappa.pkl -D data/test/cent_crop_130/
Using gpu device 0: GeForce GTX 780 (CNMeM is disabled, CuDNN 4004)
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Loading Model...
Calculating mean and std dev image...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/asif/Desktop/kaggle-dr-master/my_code/predict.py", line 74, in <module>
    cache_size_factor=_.cache_size_factor)
  File "/home/asif/Desktop/kaggle-dr-master/my_code/predict.py", line 51, in single
    column = load_column(model_file, **kwargs)
  File "/home/asif/Desktop/kaggle-dr-master/my_code/predict.py", line 43, in load_column
    column = VGGNet(data_stream, batch_size, init_learning_rate, momentum, leak_alpha, model_spec, loss_type, num_output_classes, pad, image_shape, filter_shape, cuda_convnet)
  File "my_code/VGGNet.py", line 56, in **init**
    self.x_buffer, self.y_buffer = self.ds.train_buffer().next() # dummy fill in
  File "my_code/data_stream.py", line 222, in train_buffer
    self.train_flip_lambda, self.train_color_cast_lambda)
  File "my_code/data_stream.py", line 302, in feed_image
    img = self.read_image(image_name, image_dir, crop_lambda, self.image_extension)
  File "my_code/data_stream.py", line 256, in read_image
    img = self.crop_image(img, crop_lambda) if crop_lambda else img
  File "my_code/data_stream.py", line 277, in crop_image
    t,b,l,r = crop_lambda(img)
  File "my_code/data_stream.py", line 87, in uniform_crop
    rand_t = random.randint(0, max_t)
  File "/usr/lib/python2.7/random.py", line 241, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 217, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-1, -1)

**Comment by ilyakava** [comment]
Thanks for making the issue and using the code!

The error `randrange() (0,-1, -1)` appears when you run `random.randint(0, -2)`, which means in your case the call `random.randint(0, max_t)` where [max_t](https://github.com/ilyakava/kaggle-dr/blob/b8013b60ff756a63ebd70a99d090d7491fea920c/my_code/data_stream.py#L75) is the actual image file height minus the intended image height (from [here](https://github.com/ilyakava/kaggle-dr/blob/b8013b60ff756a63ebd70a99d090d7491fea920c/my_code/data_stream.py#L174) which is [loaded from the model](https://github.com/ilyakava/kaggle-dr/blob/master/my_code/predict.py#L39)).

The image height that you trained on is two pixels larger in height than the image file you are trying to predict with, the way to fix this is to create larger test images.

p.s.
This code is in `CropOracle` [here](https://github.com/ilyakava/kaggle-dr/blob/b8013b60ff756a63ebd70a99d090d7491fea920c/my_code/data_stream.py#L69) which is mostly for cropping images down randomly from a larger size, a popular technique from Imagenet.

@zsif09 let me know more information if my guess is incorrect
